
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  - anyobject_protocol
  - block_based_kvo
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_xctest_method
  - fatal_error_message
  - file_length
  - file_types_order
  - first_where
  - last_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - override_in_extension
  - prefixed_toplevel_constant
  - private_action
  - private_over_fileprivate
  - reduce_boolean
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - yoda_condition
  - xct_specific_matcher
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - vertical_parameter_alignment_on_call
  - unused_private_declaration
included:
  - Example